version: '3'

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "9080:80"
    volumes:
      - ./docks/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticdata:/static:ro
    depends_on:
      - web

  web:
    build: .
    env_file: .env
    #command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn cutetube.wsgi -b :8000"
    volumes:
      - ./src/:/app/
      - staticdata:/static
      - mediadata:/media
    ports:
      - "8000:8000"
    entrypoint: /docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: "postgres:9.6.3"
    environment:
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  mediadata:
  staticdata:
